# Generated by Django 4.1.3 on 2022-12-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0422_multiuseinvite_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="notifications_for_all_stream_members",
            field=models.BooleanField(default=False),
        ),
    ]
